# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [1]:
import numpy

In [2]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [6]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [7]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [8]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 6.26 ms per loop


In [9]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [11]:
Z += 4

In [12]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [14]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [15]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [16]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [17]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [18]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [19]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [21]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [22]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [23]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [24]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([ 11.78220635,   8.93663103, -17.50627085, ...,  17.10257018,
         7.24243523,  -0.95099759])

## Sorting

In [25]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [26]:
print x[:10]
print x[-10:]

[ 0.00021619  0.00066141  0.0022386   0.00231872  0.00866861  0.00889664
  0.01014405  0.01216177  0.01273415  0.01466487]
[ 0.99120831  0.99250643  0.99419286  0.99490179  0.99550734  0.99653262
  0.99681669  0.99848937  0.99872478  0.99887051]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [27]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [28]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [29]:
indices[:10]

array([794,   2, 719, 257, 385, 486, 763, 772, 554, 559])

In [30]:
random_numbers.min(), random_numbers.max()

(0.0004961517756608691, 0.99889210024516806)

In [31]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(219, 0.99889210024516806)

In [32]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(794, 0.0004961517756608691)

## Exercise

In [1]:
# 0. import numpy
import numpy as np

In [15]:
# 1. sample 1000 elements from normal distribution 
s=np.random.normal(0,1,1000)
print(s)

[ -4.10090202e-01   8.18511191e-01  -1.40208831e+00  -1.72519778e+00
   3.40076956e-01   3.26031823e-01  -2.22414771e-01   1.19177714e-01
   8.35894551e-01  -8.57000031e-01  -1.47483373e+00   6.48469303e-01
   2.03350163e+00  -5.94418050e-01   8.26145067e-01   1.22814983e-01
   1.45212617e+00  -9.96606744e-01  -3.78562787e-01   7.38650138e-01
   1.98549575e+00   2.31781307e+00  -3.63803236e-01   5.00869123e-01
   1.14223322e+00  -2.28222690e-01   1.53598848e+00  -1.12950450e+00
   3.91852841e-01   1.28322411e+00  -3.35451726e-01   9.46828560e-01
   9.16458681e-02   1.71490307e-01  -7.90796977e-01   4.43850412e-02
  -2.38518056e-02  -8.47769722e-01   1.73288469e-01  -1.01077685e+00
  -4.70266912e-01   7.02803186e-01   1.91315280e-01   7.28418744e-01
  -9.99396739e-01  -1.47048321e+00   5.58400923e-01   1.06702607e+00
  -4.78720406e-01  -2.11028435e-01   6.91582823e-01  -1.44038548e-01
   1.58112889e-01  -7.24542994e-01   7.95593365e-01   1.23465432e+00
  -1.55612129e+00  -5.50201745e-01

In [27]:
# 2. leave only positive numbers (from previous exercise)
p=s[s>0]
print(p)

[ 0.81851119  0.34007696  0.32603182  0.11917771  0.83589455  0.6484693
  2.03350163  0.82614507  0.12281498  1.45212617  0.73865014  1.98549575
  2.31781307  0.50086912  1.14223322  1.53598848  0.39185284  1.28322411
  0.94682856  0.09164587  0.17149031  0.04438504  0.17328847  0.70280319
  0.19131528  0.72841874  0.55840092  1.06702607  0.69158282  0.15811289
  0.79559336  1.23465432  2.62422289  1.47406463  0.89032537  0.72128883
  0.49572691  1.36073561  0.38641196  1.5784007   1.33568682  0.418438
  0.5813146   1.1877777   0.34147144  0.78137199  1.15924008  2.1520187
  0.37424932  1.69936576  1.88448849  0.64258446  0.47944508  0.28236761
  0.89053272  0.9799513   0.9658596   0.29208113  0.61105219  1.23604083
  0.46758291  0.82350452  1.71155332  0.54315355  0.65313986  0.86613145
  0.09161238  1.16313363  0.20087665  1.14948974  1.13134184  0.13249281
  0.04393042  0.14729946  0.2025784   1.01151435  0.58270393  1.05187417
  0.67384917  0.46673113  0.5016782   0.45715363  0.635

In [28]:
# 3. count number of left numbers, their minimum, maximum, mean and variance
number=len(p)
minimum=np.min(p)
maximum=np.max(p)
mean=np.mean(p)
variance=np.std(p)
print(number, minimum, maximum, mean, variance)


516 0.00879448895145 3.0788806389 0.803762530109 0.618067856105


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
